---
#####################################
### Add users to groups
#####################################

- name: Add users to groups
  microsoft.ad.user:
    name: '{{ item.name }}'
    groups: 
        add: 
            '{{ item.group }}'
    state: present
  with_items: "{{ dc_groupmember }}"