---
#####################################
### Add users to groups statically
#####################################

#- name: Add users to groups statically
#  microsoft.ad.user:
#    name: '{{ item.name }}'
#    groups: 
#        add: 
#            '{{ item.group }}'
#  with_items: "{{ dc_groupmember_static }}"
#  when: dc_groupmember_static is defined

- name: debug
  debug:
    msg: "Esxi has ip : {{ item.0.group }} - datastore has path : {{ item.1 }}"
  loop: "{{ dc_groupmember_static | subelements('users') }}"
  loop_control:
    label: "Looping datastore {{ item.1 }} of esxi host {{ item.0.group }} "

- name: Add members to the group, preserving existing membership
  microsoft.ad.group:
    name: '{{ item.0.group }}'
    members:
      add:
        - '{{ item.1 }}'
    scope: global
  loop: "{{ dc_groupmember_static | subelements('users') }}"
  when: dc_groupmember_static is defined

#####################################
### Add users to groups dynamically
#####################################

- name: Add users to groups dynamically
  microsoft.ad.user:
    name: "{{ item.0.name | replace('##', item.1) }}"
    groups: 
        add: 
            "{{ item.0.group | replace('##', item.1) }}"
  with_nested:
  - '{{ dc_groupmember_dynamic }}'
  - '{{ range(1, dc_domain_count + 1, 1) | list }}'
  when: dc_groupmember_dynamic is defined