---
#####################################
### Add users to groups
#####################################

- name: Ensure user vagrant is member of 'Domain Admins'
  community.windows.win_domain_user:
    name: vagrant
    state: present
    groups: 'Domain Admins'

- name: Ensure users are member of 'g_g_sec_citrix_users'
  community.windows.win_domain_user:
    name: '{{ item }}'
    state: present
    groups: 'g_g_sec_citrix_users'
  loop:
    - demo
    - demo01
    - demo02
    - demo03
    - demo04
    - demo05
    - demo06
    - demo07
    - demo08
    - demo09
    - demo10