---
#####################################
### Add users to groups
#####################################

- name: Add users to groups
  community.windows.win_domain_user:
    name: '{{ item.name }}'
    groups: '{{ item.group }}'
    state: present
  with_items: "{{ groupmembers }}"