---
#####################################
### Create Group and add users statically
#####################################

- name: Add members to the group, preserving existing membership
  microsoft.ad.group:
    name: '{{ item.0.group }}'
    members:
      add:
        - '{{ item.1 }}'
    scope: global
  loop: "{{ dc_groupmember_static | subelements('users') }}"
  when: dc_groupmember_static is defined

#####################################
### Create Group and add users dynamically
#####################################

#- name: Add members to the group, preserving existing membership
#  microsoft.ad.user:
#    name: "{{ item.0.name | replace('##', item.1) }}"
#    groups: 
#        add: 
#            "{{ item.0.group | replace('##', item.1) }}"
#  with_nested:
#  - '{{ dc_groupmember_dynamic }}'
#  - '{{ range(1, dc_domain_count + 1, 1) | list }}'
#  when: dc_groupmember_dynamic is defined